spring:
  application:
    name: uss-server-prod

  datasource:
    url: ${PROD_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:database/migration
      - classpath:database/seed
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-time: 21600000
    admin-access-token-expiration-time: 7200000

inu:
  course-api:
    base-url: ${INU_API_BASE_URL}
    auth-key: ${INU_API_AUTH_KEY}
    mod-date: "20260101"

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: uss-server-prod
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,200ms,500ms,1s,2s,5s

oracle:
  datasource:
    jdbc-url: ${ORACLE_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  enabled: true

logging:
  level:
    root: INFO
    com.uss: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    p6spy: WARN
