# MySQL ????
driverlist=com.mysql.cj.jdbc.Driver

# ?? ?? ??
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=?? %(executionTime)ms | ? Query | %(sqlSingleLine)

# ?? ?? ?? (ms)
executionThreshold=0

# ?? ????
excludecategories=info,debug,result,resultset,batch,commit,rollback

# ?? ??
dateformat=yyyy-MM-dd HH:mm:ss