name: "✨ feat"
description: "새로운 기능 추가"
labels: ["feat"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
        - [ ] 작업 3
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💬 논의해볼 사항
      description: 추후 논의가 필요한 사항이 있다면 작성해 주세요.
      placeholder: 구현 방식, 기술 선택, 고려사항 등