version: '3.8'

services:
  uss-server-release:
    container_name: uss-server-release
    image: ${DOCKER_HUB_USERNAME}/uss-server:release
    ports:
      - "8282:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=release
    networks:
      - uss-release
    volumes:
      - ./logs:/var/log/spring

networks:
  uss-release:
    driver: bridge
