name: USS CD Release
on:
  push:
    branches:
      - release

jobs:
  build:
    name: JAR 생성 후, 도커 허브에 푸쉬
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: Java 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: application-release.yml 환경변수 주입
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-release.yml
        env:
          spring.datasource.url: ${{secrets.RELEASE_DATABASE_URL}}
          spring.datasource.username: ${{secrets.DATABASE_USERNAME}}
          spring.datasource.password: ${{secrets.DATABASE_PASSWORD}}

          spring.mail.username: ${{secrets.MAIL_USERNAME}}
          spring.mail.password: ${{secrets.MAIL_PASSWORD}}

          security.jwt.secret-key: ${{secrets.JWT_SECRET_KEY}}

      - name: Gradle 권한 설정
        run: chmod +x ./gradlew

      - name: JAR 빌드
        run: ./gradlew clean build -x test -i --no-daemon

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Docker 이미지 빌드
        run: docker build -f docker/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/uss-server:release .

      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/uss-server:release

  deploy:
    name: 앱센터 서버에 배포
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: SQL 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          source: "src/main/resources/sql/*.sql"
          target: "/home/serverking/uss/release"
          strip_components: 3

      - name: docker-compose-release 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          source: "docker/docker-compose-release.yml"
          target: "/home/serverking/uss/release"
          strip_components: 1

      - name: SQL 실행 및 배포
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          script: |
            cd /home/serverking/uss/release

            echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env

            echo "Executing SQL files..."

            if [ -f "sql/schema.sql" ]; then
              echo "Executing schema.sql..."
              mysql -h localhost -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} uss_db_release < sql/schema.sql
            fi

            for file in sql/course_01.sql sql/course_02.sql sql/course_03.sql; do
              if [ -f "$file" ]; then
                echo "Executing $file..."
                mysql -h localhost -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} uss_db_release < "$file"
              fi
            done

            for file in sql/course_schedule_01.sql sql/course_schedule_02.sql sql/course_schedule_03.sql; do
              if [ -f "$file" ]; then
                echo "Executing $file..."
                mysql -h localhost -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} uss_db_release < "$file"
              fi
            done

            docker-compose -f docker-compose-release.yml down
            docker-compose -f docker-compose-release.yml pull
            docker-compose -f docker-compose-release.yml up -d
            docker image prune -f
